
#* Переменные игры
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
SCREEN_TITLE = "17-th Update"
SPRITE_PIXEL_SIZE = 128
TILE_SCALING = 1
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)
FACE_RIGHT = 0
FACE_LEFT = 1

#* Переменные персонажа игры
PLAYER_SCALING = 0.5
PLAYER_START_X = 196        #* 196
PLAYER_START_Y = 200        #* 200
PLAYER_MOVEMENT_SPEED = 7
PLAYER_JUMP_SPEED = 20 #25

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
VIEWPORT_MARGIN_TOP = 150   #90
VIEWPORT_MARGIN_BOTTOM = 150   #90
VIEWPORT_RIGHT_MARGIN = 300
VIEWPORT_LEFT_MARGIN = 300

#* Переменные физики игры
MOVEMENT_SPEED = 6
JUMP_SPEED = 6
GRAVITY = 1.1
UPDATES_PER_FRAME = 7
CHARACTER_SCALING = 1
SOUND_VOLUME = 0.5
FIREBALL_SCALE = 1
FIREBALL_SPEED = 5

#* Переменные врагов
GOBLIN_SCALE = 1
ENEMY_SPEED = 7

COIN_SCALE = 1
